flowchart TD
    Start([mulai]) --> A[/forgot-password.php/]
    A --> B[input email]
    B --> C[submit]
    C --> D[cek email]
    D --> E[redirect<br/>forgot-password.php]
    E --> F[show message<br/>(email terdaftar/tidak)]
    F --> Selesai([selesai])
